version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt install python3-pip
      - run: sudo pip3 install awscli
      - run: export PATH=/root/.local/bin:$PATH
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npx semantic-release || true
      - run: python3 deploy.py
