version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install awscli --upgrade --user
      - run:
          name: install
          command: npm install
      - run:
          name: release
          command: npx semantic-release || true
      - run: python deploy.py
